version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - mkdir -p ~/.kube
        - echo $KUBE_CONFIG > ~/.kube/config
        - kubectl config set-context aws --namespace=$NAMESPACE;
        - echo "$(sed 's/!!!NAMESPACE!!!/'"$NAMESPACE"'/g' namespace.yaml)" > namespace.yaml;
        - cat namespace.yaml
        - kubectl apply -k . --prune --dry-run=server -l env0-environment-id=cdf1f932-92da-4257-80a7-1dc05950c747 --server=https://localhost:8080


destroy:
  steps:
    setupVariables:
      after: *login-k8s
